### ISSUE TITLE
Calculate total supply with Transfers

### ISSUE THREAD

**Issue by milkyklim** [trusttoken/smart-contracts#378]
I am trying to calculate total supply with `Transfer` events. I would expect 

> total supply = (total Transfer amount _from_ 0x000...000) - (total Transfer amount _to_ 0x000...000) 

formula to give me the correct totalSupply ~313866948870000000000000000 (see [contract](https://etherscan.io/address/0x0000000000085d4780b73119b644ae5ecd22b376) for up-to-date number). 
However I am about 3 times off ~106327562000000000000000000.

Is this related to Autosweep and Registar features? If so, how would you account for them?

**Comment by hal909** [comment]
Perhaps you are calculating the supply incorrectly? Autosweep could affect this. Do you have the script you used to calculate total supply?
